Experimental Actions

diff --git a/.github/workflows/deploy-on-tag.yaml b/.github/workflows/deploy-on-tag.yaml
--- a/.github/workflows/deploy-on-tag.yaml
+++ b/.github/workflows/deploy-on-tag.yaml
@@ -23,21 +23,13 @@ jobs:
         id: get-tag
         run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
 
-      - name: Get branch tagged in ${{ steps.get-tag.outputs.VERSION }}
-        id: get-tagged-branch
+      - name: Verify whether ${{ github.ref }}} tagged in deploy branch (${{ matrix.deploy-branch }})
         run: |
-          branches=$(git branch -r --contains ${{ github.ref }} | sed -e 's/origin\///g' | xargs echo)
-          echo "${{ steps.get-tag.outputs.VERSION }} is in branch(es): $branches"
-          echo ::set-output name=BRANCHES::$branches
+          BRANCHES=$(git branch -r --contains ${{ github.ref }}}
 
-      - name: Verify whether ${{ steps.get-tag.outputs.VERSION }} tagged a commit in deploy branch (${{ matrix.deploy-branch }})
-        env:
-          TAGGED_BRANCHES: ${{ steps.get-tagged-branch.outputs.BRANCHES }}
-          DEPLOY_BRANCH: ${{ matrix.deploy-branch }}
-        run: |
-          if [[ "$TAGGED_BRANCHES" != *"$DEPLOY_BRANCH"* ]]
-          then
-            echo "::error::${{ steps.get-tag.outputs.VERSION }} does not tag a commit in the expected deployment branch ($DEPLOY_BRANCH), but instead in: $TAGGED_BRANCHES"
+          $(git branch -r --contains ${{ github.ref }} | grep "origin/${{ matrix.deploy-branch }}")
+          if [[ $? -ne 0 ]]; then
+            echo "::error::${{ github.ref }} does not tag a commit in the expected deployment branch (${{ matrix.deploy-branch }}), but instead in: $BRANCHES"
             exit 1
           fi
 
